### ISSUE TITLE
форма шаблона отчета

### ISSUE THREAD

**Issue by flabser** [flabser/ComProperty#2]
Необходимо сверстать форму  report-template-form.xsl.
где будут поля 
Балансодержатель - диалог, одно значение
Тип имущества - значения с тега <propertytype> чекбокс
Тип файла отчета - значения "PDF", "XLSX" , радиокнопки, по умолчанию  PDF
 кнопка 
"Сформировать отчет"  где вызывается POST этой страницы

**Comment by medin84** [comment]
исполнено
