### ISSUE TITLE
FT Search

### ISSUE THREAD

**Issue by flabser** [flabser/ComProperty#9]
немного необходимо привести в порядок код и дописать:
1. В layout.xsl внизу я добавил код, для вызова FT-поиска, возможно требуется подправить.
2. Там же вызыватся doSearch(this,event), которая расположена в js/ftsearch.js, возможно ее надо переписать как надо и вынести куда там положено (nb.js ?) и удалить лишний js-файл.
3.  Поиск работает, но не работает pagination т.к. на кнопки перехода нужно передавать еще один параметр keyword , который приходит сейчас в виде аттрибута в XML, необходимо подправить
4. По кнопке "Возврат к списку документа", необходимо сбрасывать поле Search. Сейчас там стоит кнопка ActionType.BACK в municipalproperty.page.FTSearch.doGET(_Session, _WebFormData, LanguageType), наде ее поменять на ActionType.CUSTOM_ACTION, и написать оригинальный код, который сбрасывает поле и возвращает к списку документов 
5. При запросе если ничего не найдено то возращается сообщение в теге message, в этом случае надо его вывести в область view (Сейчас сделано там , но коряво) . В search.xsl

**Comment by medin84** [comment]
исполнено
